name = "BFReplicate"
uuid = "7f41cfe4-2318-421f-bc00-4b1a8a0f158b"
authors = ["theplatters <fscharnreitner@gmail.com>"]
version = "0.1.0"

[deps]
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"

[compat]
NonlinearSolve = "4.10.0"
